server:
  port: 8069

## spring cloud config
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# xxlJob Config
xxl:
  job:
    accessToken:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: xxl-job-executor
      address: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30